export enum ActionType {
    SET_INPUT = 'SET_INPUT',
    SET_LOCATIONS = 'SET_LOCATIONS',
    SET_LOCATION = 'SET_LOCATION',
    SET_FORECAST = 'SET_FORECAST',
    SET_IS_CELSIUS = 'SET_IS_CELSIUS',
}
